### ISSUE TITLE
启动之后，后台无法访问

### ISSUE THREAD

**Issue by banyue** [momosecurity/aswan#12]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
    self.run_application()
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 924, in run_application
    self.process_result()
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 910, in process_result
    self.write(data)
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 757, in write
    self._write_with_headers(data)
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 778, in _write_with_headers
    self._write(data)
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 742, in _write
    self._sendall(data)
  File "/usr/local/lib/python3.7/site-packages/gevent/pywsgi.py", line 704, in _sendall
    self.socket.sendall(data)
  File "/usr/local/lib/python3.7/site-packages/gevent/_socket3.py", line 457, in sendall
    data_memory = _get_memory(data)
  File "/usr/local/lib/python3.7/site-packages/gevent/_socket3.py", line 45, in _get_memory
    mv = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'
2019-07-12T11:16:49Z {'REMOTE_ADDR': '127.0.0.1', 'REMOTE_PORT': '50456', 'HTTP_HOST': 'localhost:8088', (hidden keys: 24)} failed with TypeError

请问，这是因为python3的还不能完全支持吗？

**Comment by Flynnon** [comment]
如README中所写，目前在Python3.7.3环境下进行测试，功能正常。

另外，单单贴出这个报错无法定位问题，请再完善一下场景，辅助定位问题，谢谢~
例如：在什么环境下，执行了什么操作，产生了什么结果，进行了什么尝试等，谢谢~

可以看下[提问的智慧](http://www.catb.org/~esr/faqs/smart-questions.html)，再次感谢~

**Comment by banyue** [comment]
> 如README中所写，目前在Python3.7.3环境下进行测试，功能正常。
> 
> 另外，单单贴出这个报错无法定位问题，请再完善一下场景，辅助定位问题，谢谢~
> 例如：在什么环境下，执行了什么操作，产生了什么结果，进行了什么尝试等，谢谢~
> 
> 可以看下[提问的智慧](http://www.catb.org/~esr/faqs/smart-questions.html)，再次感谢~

好的，感谢！第一次提问，已解决问题了。
