### ISSUE TITLE
bug: delete OrderedDict during iteration

### ISSUE THREAD

**Issue by islishude** [momosecurity/aswan#9]
```
Traceback (most recent call last):
  File "/Users/islishude/Library/Python/3.7/lib/python/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/islishude/Library/Python/3.7/lib/python/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/Users/islishude/project/aswan/www/permissions/middleware.py", line 45, in process_request
    if not cls.has_perm(user.email, path):
  File "/Users/islishude/project/aswan/www/permissions/middleware.py", line 51, in has_perm
    return CACHE_HAS_PERMS[(pk, path)]
  File "/Users/islishude/project/aswan/www/core/lru.py", line 39, in withlock
    return func(self, *args, **kwargs)
  File "/Users/islishude/project/aswan/www/core/lru.py", line 172, in __getitem__
    self.cleanup()
  File "/Users/islishude/project/aswan/www/core/lru.py", line 39, in withlock
    return func(self, *args, **kwargs)
  File "/Users/islishude/project/aswan/www/core/lru.py", line 189, in cleanup
    for k in self.__expire_times:
RuntimeError: OrderedDict mutated during iteration
```

I will make a PR to fix it.

**Comment by leohowell** [comment]
Well done!
